# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:      
    branches: [ master ]
  pull_request:
    branches: [ master ]

    
env:
    solutionFile: .\windows\RNW_NuGet_CSharp.sln
    manifestPath: .\windows\RNW_NuGet_CSharp\Package.appxmanifest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
          
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
          
    - name: Restore Node packages
      run: yarn install
    
    - name: Restore NuGet Packages
      run: nuget restore $env:solutionFile
        
    - name: Build
      run: msbuild $env:solutionFile /p:Configuration=$env:configuration /p:AppxBundlePlatforms=$env:platform /p:AppxBundle=Never /p:UapAppxPackageBuildMode=$env:package_build_mode /p:AppxPackageSigningEnabled=false /p:AppxPackageDir=${{github.workspace}}\AppPackages
      env:
        configuration: Release
        platform: x64
        package_build_mode: SideloadOnly
                   
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: MSIX
        # Directory containing files to upload
        path: AppPackages
      
